name: Dagger

on:
  push:
    branches: [ "main", "dagger-1" ]
env:
  REGISTRY: quay.io
  IMAGE_NAME: dagger-example
  IMAGE_TAG: ${{ github.sha }}
  USERNAME: praveen4g0
  PASSWORD: ${{ secrets.QUAY_PASSWORD }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build And Push
      run: go run dagger/dagger.go -reg ${{ env.REGISTRY }} -user ${{ env.USERNAME }} -image ${{ env.IMAGE_NAME }}  -ref ${{ env.IMAGE_TAG }}